services:
  - type: web
    name: myedupanel-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - myedupanel.com

  - type: web
    name: myedupanel-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npx prisma db push --accept-data-loss && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false